import type { Metadata } from "next";
import { Varela_Round } from "next/font/google";
import "./globals.css";

const varelaRound = Varela_Round({
  weight: "400", // Menentukan bobot font yang digunakan
  style: "normal", // Menentukan style normal
  subsets: ["latin"], // Menentukan subset karakter (misalnya latin)
  variable: "--font-varela", // Mendefinisikan custom variable CSS untuk font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${varelaRound.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
